---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgCPogf/RCadT+TXPVnXktXEkF4NlcNo6nw32//iOawsFmHWXWSGvfoPZAuEBojdUsgQw1p19knz99xaPQp2s64Cex3zgoh5aMCx9l/X8r+qplOJ2OuLReknOQNdp2g85+gYTn5/oK5a11+KUJ439fLONeRrqA6/9FRBEdONZ108guFQkdC+q2i/V+kO8fuVSyBdFedDBdGNSdFc+F/+yyQmK/ZoeRHwGEoe82Uchk5EEzu7XVlNzkHMZGqt6x4ByGa8SKtmVZi2/jfjZDPPLODInoJ1POuua0CI8ktTwuCbXvGzgHoe25SZXr4z0Rw8cJRAfDTPO5k1YprvtTRZSvLTxOkGom8xm7z7LkwKESR+GUVMXvDvkzrIJGc/bNvng83XJAi2ALaK/K68bHQVUZ64NlPLiLpy2aBIYdGPVrLK6BhaMJ++CucLzQlGJQFzalXHvsA/TYBfQn4xX7whROcMyr3kKLXgnr9nEGNcXfce4pZyl1EowUSqjEpbz2HH7yDCSPEdvdGU35jea62HkuHhVPu87nox4s1vJPDwxVuZxQqf2v6/ikQ0McKGHqy6PYf3MNFYZxjuuFis+Vrl7hyyk9Df9wiGBczPXZ6z2Zpg4j/yResqsQMJJymxr/Vx5rL8v8wYEbY06fff146tiVWjD5RNxo4nxTYrkDChONAqPAJOxysThvJDiKmoGmqQjLtomaBT0pe+LdbieoMnSvx0o8QP
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
