apiVersion: v1
kind: Service
metadata:
  name: gitops-app-service
spec:
  selector:
    app: gitops-app
  ports:
    - protocol: TCP
      port: 80       # Port, na którym usługa nasłuchuje wewnątrz klastra
      targetPort: 8080 # Port wewnątrz kontenera (z naszego Dockerfile)
      nodePort: 30080 # Port, pod którym aplikacja będzie dostępna z internetu
  type: NodePort
