---
- name: Podstawowy Hardening i Konfiguracja VPS
  hosts: lightsail
  become: yes # Mówi Ansible, aby używał 'sudo' do wykonywania zadań

  tasks:
    - name: Aktualizacja cache apt i pakietów systemowych
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalacja niezbędnych narzędzi
      apt:
        name:
          - curl
          - git
          - ufw
          - fail2ban
        state: present

    - name: UFW - Zezwól na połączenia SSH (BARDZO WAŻNE!)
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Włącz firewall
      ufw:
        state: enabled
